services:
  backend:
    build:
      context: ./backend
      dockerfile: .dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx nodemon -L server.js

  frontend:
    build:
      context: ./frontend
      dockerfile: .dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev